// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Reservation struct {
	ID        int32     `json:"id"`
	RoomID    int32     `json:"room_id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Email     string    `json:"email"`
	Phone     string    `json:"phone"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	Processed int32     `json:"processed"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Restriction struct {
	ID                int32     `json:"id"`
	RestrictionNameSr string    `json:"restriction_name_sr"`
	RestrictionNameEn string    `json:"restriction_name_en"`
	RestrictionNameBg string    `json:"restriction_name_bg"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type Room struct {
	ID                 int32     `json:"id"`
	RoomNameSr         string    `json:"room_name_sr"`
	RoomNameEn         string    `json:"room_name_en"`
	RoomNameBg         string    `json:"room_name_bg"`
	RoomShortDesSr     string    `json:"room_short_des_sr"`
	RoomShortDesEn     string    `json:"room_short_des_en"`
	RoomShortDesBg     string    `json:"room_short_des_bg"`
	RoomDescriptionSr  string    `json:"room_description_sr"`
	RoomDescriptionEn  string    `json:"room_description_en"`
	RoomDescriptionBg  string    `json:"room_description_bg"`
	RoomPicturesFolder string    `json:"room_pictures_folder"`
	RoomGuestNumber    int32     `json:"room_guest_number"`
	RoomPriceEn        int32     `json:"room_price_en"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type RoomRestriction struct {
	ID            int32       `json:"id"`
	StartDate     time.Time   `json:"start_date"`
	EndDate       time.Time   `json:"end_date"`
	RoomID        int32       `json:"room_id"`
	ReservationID pgtype.Int4 `json:"reservation_id"`
	RestrictionID int32       `json:"restriction_id"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

type User struct {
	ID          int32     `json:"id"`
	FirstName   string    `json:"first_name"`
	LastName    string    `json:"last_name"`
	Email       string    `json:"email"`
	Phone       string    `json:"phone"`
	Password    string    `json:"password"`
	AccessLevel int32     `json:"access_level"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
