// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.1
// source: rpc_list_today_activities.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListTodayActivitiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Today string `protobuf:"bytes,1,opt,name=today,proto3" json:"today,omitempty"`
}

func (x *ListTodayActivitiesRequest) Reset() {
	*x = ListTodayActivitiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_list_today_activities_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTodayActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodayActivitiesRequest) ProtoMessage() {}

func (x *ListTodayActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_list_today_activities_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodayActivitiesRequest.ProtoReflect.Descriptor instead.
func (*ListTodayActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_list_today_activities_proto_rawDescGZIP(), []int{0}
}

func (x *ListTodayActivitiesRequest) GetToday() string {
	if x != nil {
		return x.Today
	}
	return ""
}

type ListTodayActivitiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reservations []*ReservationAll `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"` // Lista reservacija
}

func (x *ListTodayActivitiesResponse) Reset() {
	*x = ListTodayActivitiesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_list_today_activities_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTodayActivitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodayActivitiesResponse) ProtoMessage() {}

func (x *ListTodayActivitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_list_today_activities_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodayActivitiesResponse.ProtoReflect.Descriptor instead.
func (*ListTodayActivitiesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_list_today_activities_proto_rawDescGZIP(), []int{1}
}

func (x *ListTodayActivitiesResponse) GetReservations() []*ReservationAll {
	if x != nil {
		return x.Reservations
	}
	return nil
}

var File_rpc_list_today_activities_proto protoreflect.FileDescriptor

var file_rpc_list_today_activities_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x72, 0x70, 0x63, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x74, 0x6f, 0x64, 0x61, 0x79,
	0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x15, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x1a,
	0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x64, 0x61, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x64, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x64, 0x61, 0x79,
	0x22, 0x55, 0x0a, 0x1b, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x64, 0x61, 0x79, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x36, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6c, 0x6c, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x69, 0x6a, 0x61, 0x6e, 0x61, 0x64, 0x6d, 0x69, 0x2f,
	0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_list_today_activities_proto_rawDescOnce sync.Once
	file_rpc_list_today_activities_proto_rawDescData = file_rpc_list_today_activities_proto_rawDesc
)

func file_rpc_list_today_activities_proto_rawDescGZIP() []byte {
	file_rpc_list_today_activities_proto_rawDescOnce.Do(func() {
		file_rpc_list_today_activities_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_list_today_activities_proto_rawDescData)
	})
	return file_rpc_list_today_activities_proto_rawDescData
}

var file_rpc_list_today_activities_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_list_today_activities_proto_goTypes = []any{
	(*ListTodayActivitiesRequest)(nil),  // 0: pb.ListTodayActivitiesRequest
	(*ListTodayActivitiesResponse)(nil), // 1: pb.ListTodayActivitiesResponse
	(*ReservationAll)(nil),              // 2: pb.ReservationAll
}
var file_rpc_list_today_activities_proto_depIdxs = []int32{
	2, // 0: pb.ListTodayActivitiesResponse.reservations:type_name -> pb.ReservationAll
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_list_today_activities_proto_init() }
func file_rpc_list_today_activities_proto_init() {
	if File_rpc_list_today_activities_proto != nil {
		return
	}
	file_reservation_all_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_list_today_activities_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ListTodayActivitiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_list_today_activities_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ListTodayActivitiesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_list_today_activities_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_list_today_activities_proto_goTypes,
		DependencyIndexes: file_rpc_list_today_activities_proto_depIdxs,
		MessageInfos:      file_rpc_list_today_activities_proto_msgTypes,
	}.Build()
	File_rpc_list_today_activities_proto = out.File
	file_rpc_list_today_activities_proto_rawDesc = nil
	file_rpc_list_today_activities_proto_goTypes = nil
	file_rpc_list_today_activities_proto_depIdxs = nil
}
