// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: service_bookings_backend.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Bookings_CreateUser_FullMethodName                    = "/pb.Bookings/CreateUser"
	Bookings_GetUser_FullMethodName                       = "/pb.Bookings/GetUser"
	Bookings_GetUserByToken_FullMethodName                = "/pb.Bookings/GetUserByToken"
	Bookings_UpdateUser_FullMethodName                    = "/pb.Bookings/UpdateUser"
	Bookings_LoginUser_FullMethodName                     = "/pb.Bookings/LoginUser"
	Bookings_RefreshToken_FullMethodName                  = "/pb.Bookings/RefreshToken"
	Bookings_GetRoom_FullMethodName                       = "/pb.Bookings/GetRoom"
	Bookings_ListRooms_FullMethodName                     = "/pb.Bookings/ListRooms"
	Bookings_SearchAvailabilityForAllRooms_FullMethodName = "/pb.Bookings/SearchAvailabilityForAllRooms"
	Bookings_CreateRoom_FullMethodName                    = "/pb.Bookings/CreateRoom"
	Bookings_UpdateRoom_FullMethodName                    = "/pb.Bookings/UpdateRoom"
	Bookings_DeleteRoom_FullMethodName                    = "/pb.Bookings/DeleteRoom"
	Bookings_CreateRestriction_FullMethodName             = "/pb.Bookings/CreateRestriction"
	Bookings_GetRestriction_FullMethodName                = "/pb.Bookings/GetRestriction"
	Bookings_ListRestrictions_FullMethodName              = "/pb.Bookings/ListRestrictions"
	Bookings_UpdateRestriction_FullMethodName             = "/pb.Bookings/UpdateRestriction"
	Bookings_DeleteRestriction_FullMethodName             = "/pb.Bookings/DeleteRestriction"
	Bookings_GetReservation_FullMethodName                = "/pb.Bookings/GetReservation"
	Bookings_ListAllReservations_FullMethodName           = "/pb.Bookings/ListAllReservations"
	Bookings_ListNewReservations_FullMethodName           = "/pb.Bookings/ListNewReservations"
	Bookings_ListProcessedReservations_FullMethodName     = "/pb.Bookings/ListProcessedReservations"
	Bookings_ListReservationsWithParams_FullMethodName    = "/pb.Bookings/ListReservationsWithParams"
	Bookings_ListReservationsAfterDate_FullMethodName     = "/pb.Bookings/ListReservationsAfterDate"
	Bookings_ListStaysAfterDate_FullMethodName            = "/pb.Bookings/ListStaysAfterDate"
	Bookings_ListTodayActivities_FullMethodName           = "/pb.Bookings/ListTodayActivities"
	Bookings_CreateReservation_FullMethodName             = "/pb.Bookings/CreateReservation"
	Bookings_UpdateReservation_FullMethodName             = "/pb.Bookings/UpdateReservation"
	Bookings_DeleteReservation_FullMethodName             = "/pb.Bookings/DeleteReservation"
	Bookings_CreateRoomRestriction_FullMethodName         = "/pb.Bookings/CreateRoomRestriction"
)

// BookingsClient is the client API for Bookings service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookingsClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	GetUserByToken(ctx context.Context, in *GetUserByTokenRequest, opts ...grpc.CallOption) (*GetUserByTokenResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*GetRoomResponse, error)
	ListRooms(ctx context.Context, in *ListRoomsRequest, opts ...grpc.CallOption) (*ListRoomsResponse, error)
	SearchAvailabilityForAllRooms(ctx context.Context, in *SearchAvailabilityForAllRoomsRequest, opts ...grpc.CallOption) (*SearchAvailabilityForAllRoomsResponse, error)
	CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomResponse, error)
	UpdateRoom(ctx context.Context, in *UpdateRoomRequest, opts ...grpc.CallOption) (*UpdateRoomResponse, error)
	DeleteRoom(ctx context.Context, in *DeleteRoomRequest, opts ...grpc.CallOption) (*DeleteRoomResponse, error)
	CreateRestriction(ctx context.Context, in *CreateRestrictionRequest, opts ...grpc.CallOption) (*CreateRestrictionResponse, error)
	GetRestriction(ctx context.Context, in *GetRestrictionRequest, opts ...grpc.CallOption) (*GetRestrictionResponse, error)
	ListRestrictions(ctx context.Context, in *ListRestrictionsRequest, opts ...grpc.CallOption) (*ListRestrictionsResponse, error)
	UpdateRestriction(ctx context.Context, in *UpdateRestrictionRequest, opts ...grpc.CallOption) (*UpdateRestrictionResponse, error)
	DeleteRestriction(ctx context.Context, in *DeleteRestrictionRequest, opts ...grpc.CallOption) (*DeleteRestrictionResponse, error)
	GetReservation(ctx context.Context, in *GetReservationRequest, opts ...grpc.CallOption) (*GetReservationResponse, error)
	ListAllReservations(ctx context.Context, in *ListAllReservationsRequest, opts ...grpc.CallOption) (*ListAllReservationsResponse, error)
	ListNewReservations(ctx context.Context, in *ListNewReservationsRequest, opts ...grpc.CallOption) (*ListNewReservationsResponse, error)
	ListProcessedReservations(ctx context.Context, in *ListProcessedReservationsRequest, opts ...grpc.CallOption) (*ListProcessedReservationsResponse, error)
	ListReservationsWithParams(ctx context.Context, in *ListReservationsParamsRequest, opts ...grpc.CallOption) (*ListReservationsParamsResponse, error)
	ListReservationsAfterDate(ctx context.Context, in *ListReservationsAfterDateRequest, opts ...grpc.CallOption) (*ListReservationsAfterDateResponse, error)
	ListStaysAfterDate(ctx context.Context, in *ListStaysAfterDateRequest, opts ...grpc.CallOption) (*ListStaysAfterDateResponse, error)
	ListTodayActivities(ctx context.Context, in *ListTodayActivitiesRequest, opts ...grpc.CallOption) (*ListTodayActivitiesResponse, error)
	CreateReservation(ctx context.Context, in *CreateReservationRequest, opts ...grpc.CallOption) (*CreateReservationResponse, error)
	UpdateReservation(ctx context.Context, in *UpdateReservationRequest, opts ...grpc.CallOption) (*UpdateReservationResponse, error)
	DeleteReservation(ctx context.Context, in *DeleteReservationRequest, opts ...grpc.CallOption) (*DeleteReservationResponse, error)
	CreateRoomRestriction(ctx context.Context, in *CreateRoomRestrictionRequest, opts ...grpc.CallOption) (*CreateRoomRestrictionResponse, error)
}

type bookingsClient struct {
	cc grpc.ClientConnInterface
}

func NewBookingsClient(cc grpc.ClientConnInterface) BookingsClient {
	return &bookingsClient{cc}
}

func (c *bookingsClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, Bookings_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, Bookings_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) GetUserByToken(ctx context.Context, in *GetUserByTokenRequest, opts ...grpc.CallOption) (*GetUserByTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserByTokenResponse)
	err := c.cc.Invoke(ctx, Bookings_GetUserByToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, Bookings_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, Bookings_LoginUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, Bookings_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*GetRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoomResponse)
	err := c.cc.Invoke(ctx, Bookings_GetRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) ListRooms(ctx context.Context, in *ListRoomsRequest, opts ...grpc.CallOption) (*ListRoomsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoomsResponse)
	err := c.cc.Invoke(ctx, Bookings_ListRooms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) SearchAvailabilityForAllRooms(ctx context.Context, in *SearchAvailabilityForAllRoomsRequest, opts ...grpc.CallOption) (*SearchAvailabilityForAllRoomsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchAvailabilityForAllRoomsResponse)
	err := c.cc.Invoke(ctx, Bookings_SearchAvailabilityForAllRooms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRoomResponse)
	err := c.cc.Invoke(ctx, Bookings_CreateRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) UpdateRoom(ctx context.Context, in *UpdateRoomRequest, opts ...grpc.CallOption) (*UpdateRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRoomResponse)
	err := c.cc.Invoke(ctx, Bookings_UpdateRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) DeleteRoom(ctx context.Context, in *DeleteRoomRequest, opts ...grpc.CallOption) (*DeleteRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRoomResponse)
	err := c.cc.Invoke(ctx, Bookings_DeleteRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) CreateRestriction(ctx context.Context, in *CreateRestrictionRequest, opts ...grpc.CallOption) (*CreateRestrictionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRestrictionResponse)
	err := c.cc.Invoke(ctx, Bookings_CreateRestriction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) GetRestriction(ctx context.Context, in *GetRestrictionRequest, opts ...grpc.CallOption) (*GetRestrictionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRestrictionResponse)
	err := c.cc.Invoke(ctx, Bookings_GetRestriction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) ListRestrictions(ctx context.Context, in *ListRestrictionsRequest, opts ...grpc.CallOption) (*ListRestrictionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRestrictionsResponse)
	err := c.cc.Invoke(ctx, Bookings_ListRestrictions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) UpdateRestriction(ctx context.Context, in *UpdateRestrictionRequest, opts ...grpc.CallOption) (*UpdateRestrictionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRestrictionResponse)
	err := c.cc.Invoke(ctx, Bookings_UpdateRestriction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) DeleteRestriction(ctx context.Context, in *DeleteRestrictionRequest, opts ...grpc.CallOption) (*DeleteRestrictionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRestrictionResponse)
	err := c.cc.Invoke(ctx, Bookings_DeleteRestriction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) GetReservation(ctx context.Context, in *GetReservationRequest, opts ...grpc.CallOption) (*GetReservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReservationResponse)
	err := c.cc.Invoke(ctx, Bookings_GetReservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) ListAllReservations(ctx context.Context, in *ListAllReservationsRequest, opts ...grpc.CallOption) (*ListAllReservationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAllReservationsResponse)
	err := c.cc.Invoke(ctx, Bookings_ListAllReservations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) ListNewReservations(ctx context.Context, in *ListNewReservationsRequest, opts ...grpc.CallOption) (*ListNewReservationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNewReservationsResponse)
	err := c.cc.Invoke(ctx, Bookings_ListNewReservations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) ListProcessedReservations(ctx context.Context, in *ListProcessedReservationsRequest, opts ...grpc.CallOption) (*ListProcessedReservationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProcessedReservationsResponse)
	err := c.cc.Invoke(ctx, Bookings_ListProcessedReservations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) ListReservationsWithParams(ctx context.Context, in *ListReservationsParamsRequest, opts ...grpc.CallOption) (*ListReservationsParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReservationsParamsResponse)
	err := c.cc.Invoke(ctx, Bookings_ListReservationsWithParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) ListReservationsAfterDate(ctx context.Context, in *ListReservationsAfterDateRequest, opts ...grpc.CallOption) (*ListReservationsAfterDateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReservationsAfterDateResponse)
	err := c.cc.Invoke(ctx, Bookings_ListReservationsAfterDate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) ListStaysAfterDate(ctx context.Context, in *ListStaysAfterDateRequest, opts ...grpc.CallOption) (*ListStaysAfterDateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStaysAfterDateResponse)
	err := c.cc.Invoke(ctx, Bookings_ListStaysAfterDate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) ListTodayActivities(ctx context.Context, in *ListTodayActivitiesRequest, opts ...grpc.CallOption) (*ListTodayActivitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTodayActivitiesResponse)
	err := c.cc.Invoke(ctx, Bookings_ListTodayActivities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) CreateReservation(ctx context.Context, in *CreateReservationRequest, opts ...grpc.CallOption) (*CreateReservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReservationResponse)
	err := c.cc.Invoke(ctx, Bookings_CreateReservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) UpdateReservation(ctx context.Context, in *UpdateReservationRequest, opts ...grpc.CallOption) (*UpdateReservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateReservationResponse)
	err := c.cc.Invoke(ctx, Bookings_UpdateReservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) DeleteReservation(ctx context.Context, in *DeleteReservationRequest, opts ...grpc.CallOption) (*DeleteReservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteReservationResponse)
	err := c.cc.Invoke(ctx, Bookings_DeleteReservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsClient) CreateRoomRestriction(ctx context.Context, in *CreateRoomRestrictionRequest, opts ...grpc.CallOption) (*CreateRoomRestrictionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRoomRestrictionResponse)
	err := c.cc.Invoke(ctx, Bookings_CreateRoomRestriction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookingsServer is the server API for Bookings service.
// All implementations must embed UnimplementedBookingsServer
// for forward compatibility.
type BookingsServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	GetUserByToken(context.Context, *GetUserByTokenRequest) (*GetUserByTokenResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	GetRoom(context.Context, *GetRoomRequest) (*GetRoomResponse, error)
	ListRooms(context.Context, *ListRoomsRequest) (*ListRoomsResponse, error)
	SearchAvailabilityForAllRooms(context.Context, *SearchAvailabilityForAllRoomsRequest) (*SearchAvailabilityForAllRoomsResponse, error)
	CreateRoom(context.Context, *CreateRoomRequest) (*CreateRoomResponse, error)
	UpdateRoom(context.Context, *UpdateRoomRequest) (*UpdateRoomResponse, error)
	DeleteRoom(context.Context, *DeleteRoomRequest) (*DeleteRoomResponse, error)
	CreateRestriction(context.Context, *CreateRestrictionRequest) (*CreateRestrictionResponse, error)
	GetRestriction(context.Context, *GetRestrictionRequest) (*GetRestrictionResponse, error)
	ListRestrictions(context.Context, *ListRestrictionsRequest) (*ListRestrictionsResponse, error)
	UpdateRestriction(context.Context, *UpdateRestrictionRequest) (*UpdateRestrictionResponse, error)
	DeleteRestriction(context.Context, *DeleteRestrictionRequest) (*DeleteRestrictionResponse, error)
	GetReservation(context.Context, *GetReservationRequest) (*GetReservationResponse, error)
	ListAllReservations(context.Context, *ListAllReservationsRequest) (*ListAllReservationsResponse, error)
	ListNewReservations(context.Context, *ListNewReservationsRequest) (*ListNewReservationsResponse, error)
	ListProcessedReservations(context.Context, *ListProcessedReservationsRequest) (*ListProcessedReservationsResponse, error)
	ListReservationsWithParams(context.Context, *ListReservationsParamsRequest) (*ListReservationsParamsResponse, error)
	ListReservationsAfterDate(context.Context, *ListReservationsAfterDateRequest) (*ListReservationsAfterDateResponse, error)
	ListStaysAfterDate(context.Context, *ListStaysAfterDateRequest) (*ListStaysAfterDateResponse, error)
	ListTodayActivities(context.Context, *ListTodayActivitiesRequest) (*ListTodayActivitiesResponse, error)
	CreateReservation(context.Context, *CreateReservationRequest) (*CreateReservationResponse, error)
	UpdateReservation(context.Context, *UpdateReservationRequest) (*UpdateReservationResponse, error)
	DeleteReservation(context.Context, *DeleteReservationRequest) (*DeleteReservationResponse, error)
	CreateRoomRestriction(context.Context, *CreateRoomRestrictionRequest) (*CreateRoomRestrictionResponse, error)
	mustEmbedUnimplementedBookingsServer()
}

// UnimplementedBookingsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBookingsServer struct{}

func (UnimplementedBookingsServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedBookingsServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedBookingsServer) GetUserByToken(context.Context, *GetUserByTokenRequest) (*GetUserByTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByToken not implemented")
}
func (UnimplementedBookingsServer) UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedBookingsServer) LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedBookingsServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedBookingsServer) GetRoom(context.Context, *GetRoomRequest) (*GetRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoom not implemented")
}
func (UnimplementedBookingsServer) ListRooms(context.Context, *ListRoomsRequest) (*ListRoomsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRooms not implemented")
}
func (UnimplementedBookingsServer) SearchAvailabilityForAllRooms(context.Context, *SearchAvailabilityForAllRoomsRequest) (*SearchAvailabilityForAllRoomsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchAvailabilityForAllRooms not implemented")
}
func (UnimplementedBookingsServer) CreateRoom(context.Context, *CreateRoomRequest) (*CreateRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoom not implemented")
}
func (UnimplementedBookingsServer) UpdateRoom(context.Context, *UpdateRoomRequest) (*UpdateRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoom not implemented")
}
func (UnimplementedBookingsServer) DeleteRoom(context.Context, *DeleteRoomRequest) (*DeleteRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRoom not implemented")
}
func (UnimplementedBookingsServer) CreateRestriction(context.Context, *CreateRestrictionRequest) (*CreateRestrictionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRestriction not implemented")
}
func (UnimplementedBookingsServer) GetRestriction(context.Context, *GetRestrictionRequest) (*GetRestrictionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRestriction not implemented")
}
func (UnimplementedBookingsServer) ListRestrictions(context.Context, *ListRestrictionsRequest) (*ListRestrictionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRestrictions not implemented")
}
func (UnimplementedBookingsServer) UpdateRestriction(context.Context, *UpdateRestrictionRequest) (*UpdateRestrictionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRestriction not implemented")
}
func (UnimplementedBookingsServer) DeleteRestriction(context.Context, *DeleteRestrictionRequest) (*DeleteRestrictionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRestriction not implemented")
}
func (UnimplementedBookingsServer) GetReservation(context.Context, *GetReservationRequest) (*GetReservationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReservation not implemented")
}
func (UnimplementedBookingsServer) ListAllReservations(context.Context, *ListAllReservationsRequest) (*ListAllReservationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAllReservations not implemented")
}
func (UnimplementedBookingsServer) ListNewReservations(context.Context, *ListNewReservationsRequest) (*ListNewReservationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNewReservations not implemented")
}
func (UnimplementedBookingsServer) ListProcessedReservations(context.Context, *ListProcessedReservationsRequest) (*ListProcessedReservationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProcessedReservations not implemented")
}
func (UnimplementedBookingsServer) ListReservationsWithParams(context.Context, *ListReservationsParamsRequest) (*ListReservationsParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReservationsWithParams not implemented")
}
func (UnimplementedBookingsServer) ListReservationsAfterDate(context.Context, *ListReservationsAfterDateRequest) (*ListReservationsAfterDateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReservationsAfterDate not implemented")
}
func (UnimplementedBookingsServer) ListStaysAfterDate(context.Context, *ListStaysAfterDateRequest) (*ListStaysAfterDateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStaysAfterDate not implemented")
}
func (UnimplementedBookingsServer) ListTodayActivities(context.Context, *ListTodayActivitiesRequest) (*ListTodayActivitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTodayActivities not implemented")
}
func (UnimplementedBookingsServer) CreateReservation(context.Context, *CreateReservationRequest) (*CreateReservationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReservation not implemented")
}
func (UnimplementedBookingsServer) UpdateReservation(context.Context, *UpdateReservationRequest) (*UpdateReservationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateReservation not implemented")
}
func (UnimplementedBookingsServer) DeleteReservation(context.Context, *DeleteReservationRequest) (*DeleteReservationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteReservation not implemented")
}
func (UnimplementedBookingsServer) CreateRoomRestriction(context.Context, *CreateRoomRestrictionRequest) (*CreateRoomRestrictionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoomRestriction not implemented")
}
func (UnimplementedBookingsServer) mustEmbedUnimplementedBookingsServer() {}
func (UnimplementedBookingsServer) testEmbeddedByValue()                  {}

// UnsafeBookingsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookingsServer will
// result in compilation errors.
type UnsafeBookingsServer interface {
	mustEmbedUnimplementedBookingsServer()
}

func RegisterBookingsServer(s grpc.ServiceRegistrar, srv BookingsServer) {
	// If the following call pancis, it indicates UnimplementedBookingsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Bookings_ServiceDesc, srv)
}

func _Bookings_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_GetUserByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).GetUserByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_GetUserByToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).GetUserByToken(ctx, req.(*GetUserByTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_LoginUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_GetRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).GetRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_GetRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).GetRoom(ctx, req.(*GetRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_ListRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoomsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).ListRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_ListRooms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).ListRooms(ctx, req.(*ListRoomsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_SearchAvailabilityForAllRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchAvailabilityForAllRoomsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).SearchAvailabilityForAllRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_SearchAvailabilityForAllRooms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).SearchAvailabilityForAllRooms(ctx, req.(*SearchAvailabilityForAllRoomsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_CreateRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).CreateRoom(ctx, req.(*CreateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_UpdateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).UpdateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_UpdateRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).UpdateRoom(ctx, req.(*UpdateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_DeleteRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).DeleteRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_DeleteRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).DeleteRoom(ctx, req.(*DeleteRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_CreateRestriction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRestrictionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).CreateRestriction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_CreateRestriction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).CreateRestriction(ctx, req.(*CreateRestrictionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_GetRestriction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRestrictionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).GetRestriction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_GetRestriction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).GetRestriction(ctx, req.(*GetRestrictionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_ListRestrictions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRestrictionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).ListRestrictions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_ListRestrictions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).ListRestrictions(ctx, req.(*ListRestrictionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_UpdateRestriction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRestrictionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).UpdateRestriction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_UpdateRestriction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).UpdateRestriction(ctx, req.(*UpdateRestrictionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_DeleteRestriction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRestrictionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).DeleteRestriction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_DeleteRestriction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).DeleteRestriction(ctx, req.(*DeleteRestrictionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_GetReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).GetReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_GetReservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).GetReservation(ctx, req.(*GetReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_ListAllReservations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllReservationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).ListAllReservations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_ListAllReservations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).ListAllReservations(ctx, req.(*ListAllReservationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_ListNewReservations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNewReservationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).ListNewReservations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_ListNewReservations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).ListNewReservations(ctx, req.(*ListNewReservationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_ListProcessedReservations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProcessedReservationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).ListProcessedReservations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_ListProcessedReservations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).ListProcessedReservations(ctx, req.(*ListProcessedReservationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_ListReservationsWithParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReservationsParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).ListReservationsWithParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_ListReservationsWithParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).ListReservationsWithParams(ctx, req.(*ListReservationsParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_ListReservationsAfterDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReservationsAfterDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).ListReservationsAfterDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_ListReservationsAfterDate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).ListReservationsAfterDate(ctx, req.(*ListReservationsAfterDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_ListStaysAfterDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStaysAfterDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).ListStaysAfterDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_ListStaysAfterDate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).ListStaysAfterDate(ctx, req.(*ListStaysAfterDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_ListTodayActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTodayActivitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).ListTodayActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_ListTodayActivities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).ListTodayActivities(ctx, req.(*ListTodayActivitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_CreateReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).CreateReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_CreateReservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).CreateReservation(ctx, req.(*CreateReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_UpdateReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).UpdateReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_UpdateReservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).UpdateReservation(ctx, req.(*UpdateReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_DeleteReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).DeleteReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_DeleteReservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).DeleteReservation(ctx, req.(*DeleteReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookings_CreateRoomRestriction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoomRestrictionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServer).CreateRoomRestriction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bookings_CreateRoomRestriction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServer).CreateRoomRestriction(ctx, req.(*CreateRoomRestrictionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Bookings_ServiceDesc is the grpc.ServiceDesc for Bookings service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bookings_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Bookings",
	HandlerType: (*BookingsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _Bookings_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Bookings_GetUser_Handler,
		},
		{
			MethodName: "GetUserByToken",
			Handler:    _Bookings_GetUserByToken_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _Bookings_UpdateUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _Bookings_LoginUser_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _Bookings_RefreshToken_Handler,
		},
		{
			MethodName: "GetRoom",
			Handler:    _Bookings_GetRoom_Handler,
		},
		{
			MethodName: "ListRooms",
			Handler:    _Bookings_ListRooms_Handler,
		},
		{
			MethodName: "SearchAvailabilityForAllRooms",
			Handler:    _Bookings_SearchAvailabilityForAllRooms_Handler,
		},
		{
			MethodName: "CreateRoom",
			Handler:    _Bookings_CreateRoom_Handler,
		},
		{
			MethodName: "UpdateRoom",
			Handler:    _Bookings_UpdateRoom_Handler,
		},
		{
			MethodName: "DeleteRoom",
			Handler:    _Bookings_DeleteRoom_Handler,
		},
		{
			MethodName: "CreateRestriction",
			Handler:    _Bookings_CreateRestriction_Handler,
		},
		{
			MethodName: "GetRestriction",
			Handler:    _Bookings_GetRestriction_Handler,
		},
		{
			MethodName: "ListRestrictions",
			Handler:    _Bookings_ListRestrictions_Handler,
		},
		{
			MethodName: "UpdateRestriction",
			Handler:    _Bookings_UpdateRestriction_Handler,
		},
		{
			MethodName: "DeleteRestriction",
			Handler:    _Bookings_DeleteRestriction_Handler,
		},
		{
			MethodName: "GetReservation",
			Handler:    _Bookings_GetReservation_Handler,
		},
		{
			MethodName: "ListAllReservations",
			Handler:    _Bookings_ListAllReservations_Handler,
		},
		{
			MethodName: "ListNewReservations",
			Handler:    _Bookings_ListNewReservations_Handler,
		},
		{
			MethodName: "ListProcessedReservations",
			Handler:    _Bookings_ListProcessedReservations_Handler,
		},
		{
			MethodName: "ListReservationsWithParams",
			Handler:    _Bookings_ListReservationsWithParams_Handler,
		},
		{
			MethodName: "ListReservationsAfterDate",
			Handler:    _Bookings_ListReservationsAfterDate_Handler,
		},
		{
			MethodName: "ListStaysAfterDate",
			Handler:    _Bookings_ListStaysAfterDate_Handler,
		},
		{
			MethodName: "ListTodayActivities",
			Handler:    _Bookings_ListTodayActivities_Handler,
		},
		{
			MethodName: "CreateReservation",
			Handler:    _Bookings_CreateReservation_Handler,
		},
		{
			MethodName: "UpdateReservation",
			Handler:    _Bookings_UpdateReservation_Handler,
		},
		{
			MethodName: "DeleteReservation",
			Handler:    _Bookings_DeleteReservation_Handler,
		},
		{
			MethodName: "CreateRoomRestriction",
			Handler:    _Bookings_CreateRoomRestriction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_bookings_backend.proto",
}
